name: node_http
description: HTTP client powered by Node.js I/O system.
version: 1.0.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  node_interop:
    git:
      url: https://github.com/SwissCheese5/node-interop.git
      path: node_interop
  node_io:
    git:
      url: https://github.com/SwissCheese5/node-interop.git
      path: node_io

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers:
    git:
      url: https://github.com/SwissCheese5/node-interop.git
      path: build_node_compilers
  build_test:
  pedantic: ^1.0.0
  test: ^1.0.0
