name: node_io
description: Like dart:io but with Node.js.
version: 1.1.1
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  node_interop:
    git:
      url: https://github.com/SwissCheese5/node-interop.git
      path: node_interop
  path: ^1.6.2

dev_dependencies:
  js: ^0.6.0
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  build_test:
  build_node_compilers:
    git:
      url: https://github.com/SwissCheese5/node-interop.git
      path: build_node_compilers
